Feature/402 all attributes as text columns
claeis/ili2db pull request #416
Opened 2021-08-05 15:42 UTC by rbotteon

### Szenario:

- **import**

1. Test Datei `Datatypes23Attr_textLimitedTooLong.xtf` enthält die werte `textLimited` dass ist länger als definiert in `Datatypes23.ili`
1. Import mit flag `--xtfAttrsAsText` (_Datatypes23Test#importXtfAttr_asText)
1. Die Schema wird generiert, jede spalte ist _DbColVarchar_.UNLIMITED ausser die definierte in _AbstractRecordConverter#shouldBeSkipped_
1. Die werten werden von xft importiert und als TEXT in db gespeichert ausser die definierte in AbstractRecordConverter#shouldBeSkipped
1. In Test importXtfAttr_asText wird kontrolliert dass die werten sind genau (inkl. case) dir gleichen als in xtf

- **export**
1. Export mit flag `--xtfAttrsAsText` (_Datatypes23Test#exportXtfAttr_invalidTextLimited)
1. Jede attribute wird gelesen als string ausser die definierte in _AbstractRecordConverter#shouldBeSkipped_
1. In Test exportXtfAttr_invalidTextLimited wird kontrolliert dass die werten sind genau (inkl. case) dir gleichen als in der originell 

Bei ein export ohne flag `--xtfAttrsAsText` von invalide xtf Daten die export wird failen (wie erwartet)

2021-08-06 08:12 UTC, claeis requested changes
...und neue Funktion bitte in Doku ergänzen

2021-08-06 08:12 UTC, claeis commented on src/ch/ehi/ili2db/gui/Config.java
> +	public boolean isXtfAttrText() {
wie SQL_NULL implementieren, damit die Einstellung in die t_ili2db_settings Tabelle gespeichert wird (und der Benutzer somit beim --import/--export nicht mehr wissen/angeben muss)

2021-08-06 08:12 UTC, claeis commented on src/ch/ehi/ili2db/toxtf/TransferToXtf.java
> +			modelConfig.setConfigValue(ValidationConfig.PARAMETER, ValidationConfig.VALIDATION, config.isXtfAttrText()?ValidationConfig.OFF:ValidationConfig.ON);
Validierung nicht ausschalten! Wenn der Benutzer nicht valide Daten exportieren will, soll er das bewusst tun (indem er explizit die Validierung ausschaltet)

2021-08-06 08:12 UTC, claeis commented on test/data/Datatypes23/Datatypes23Attr_textLimitedTooLong.xtf
> +				<textLimited>1111111111111111111111111111111111111111</textLimited>
Die Option betrifft ja nicht nur zu lange Text-Attribute, sondern alle simple-Type Attribute, also Test erweitern, so dass z.B. auch für die Aufzählung Werte importiert werden, die nicht in der Aufzählung vorkommen, oder Datumswerte, die keine Datum sind, oder Text bei Zahlen-Attribute usw.

2021-08-06 08:12 UTC, claeis commented on test/java/ch/ehi/ili2db/Datatypes23Test.java
> +			config.setXtfAttrText(true);
...und Validierung ausschalten.

2021-08-06 08:12 UTC, claeis commented on test/java/ch/ehi/ili2db/Datatypes23Test.java
> +			config.setXtfAttrText(true);
...und Validierung explizit ausschalten.

2021-08-09 11:09 UTC, rbotteon commented
@claeis 
Salü Claude,

danke für dein Feedback!
Jetzt ich habe alle Änderungen implementiert gemäss deine Kommentare.

Ruggero

2021-08-09 12:31 UTC, rbotteon commented
Ich hatte in docx dokumentiert, changes reverted und ist jetzt in rst dokimentiert.

2021-08-09 13:03 UTC, claeis requested changes

2021-08-09 13:03 UTC, claeis commented on docs/ili2db.rst
> +| --sqlColsAsText               | Bei import alle die Simple Types werden als Text gespeichert. Bei export alle die SimpleType werden als String gelesen. In beide fälle der User muss die Validation d
Es ist eine --schemaimport Option (und nicht eine --import/--export Option). Darum/Vorschlag:
  
      Bildet alle (einfachen/unstrukturierten) Interlis-Attribute als TEXT-Spalten ab, so dass fehlerhafte Daten importiert werden können.

Und bitte auch bei https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst#fehlerhafte-daten ergänzen.

2021-08-09 13:25 UTC, rbotteon commented
Done!

2021-08-09 14:52 UTC, merged