Feature/334 jdbc fetchsize batchsize
claeis/ili2db pull request #417
Opened 2021-08-05 15:45 UTC by rbotteon

### Szenario:

- **fetchsize**
wird gesetzt in export (wenn die Option ist gegeben) bei allen Nutzdaten statements

- **batchsize**
wird gesetzt in import (wenn die Option ist gegeben), bei allen statements dass ich habe sinnvoll gefunden

2021-08-06 09:56 UTC, claeis requested changes
Bitte
 
- für Tests je eine neue Test-Klasse erstellen BatchTest, FetchTest (und bestehende Tests nicht ändern); und so machen, das sie für ili2pg und ili2gpkg laufen (Muster: SimpleTest)
- neue Programmoptionen in Doku ergänzen

(Hätte zwei getrennte PRs (einer Batch, der andere Fetch) bevorzugt, aber ok, lässt sich jetzt wohl nicht mehr ändern.)

2021-08-06 09:56 UTC, claeis commented on src/ch/ehi/ili2db/AbstractMain.java
> +            }else if(arg.equals("-importFetchSize")){
hier fehlt ein -

2021-08-06 09:56 UTC, claeis commented on src/ch/ehi/ili2db/base/StatementExecutionHelper.java
> +    public void executeSingleOrBatch(PreparedStatement ps, boolean isLastStatement) throws SQLException {
wäre es nicht besser (im Interface der Klasse) auf das Flag isLastStatement zu verzichten, und stattdessen zwei Funktionen zu machen: write(ps) und flush(ps)?

2021-08-09 15:56 UTC, rbotteon commented
Alles done :)

Merci und eine schonen Abend.

2021-08-10 08:08 UTC, claeis requested changes
Danke. Finde die Implementierung gut. Bei den Tests bitte noch ein wenig nachbessern.

2021-08-10 08:08 UTC, claeis commented on test/java/ch/ehi/ili2db/BatchTest.java
> +        File data=new File(TEST_OUT,"BatchSize.xtf");
Wahrscheinlich macht es mehr Sinn, hier für diesen Test das XTF zu erzeugen und dann dieses zu Importieren.

2021-08-10 08:08 UTC, claeis commented on test/java/ch/ehi/ili2db/FetchTest.java
> +            importXtf();
Wahrscheinlich macht es mehr Sinn, hier für diesen Test nur ein Schema-Import zu machen (importIli()) und dann in der Tabelle mit SQL Records zu erzeugen und dann den Export  zu machen.

2021-08-10 08:08 UTC, claeis commented on test/data/BatchSize/BatchSize.xtf
> +			<Rounding23.Topic.ClassAttr TID="Attr.1">
Wenn es nur ein Objekt pro Klasse hat, testet das den "Batch" Mechanismus nicht wirklich

2021-08-10 08:08 UTC, claeis commented on test/data/FetchSize/FetchSize.xtf
> +			<Rounding23.Topic.ClassAttr TID="Attr.1">
Wenn es nur ein Objekt pro Klasse gibt, testet das den "Fetch" Mechansimus nicht

2021-08-19 15:06 UTC, merged