Add support for --option=booleanValue
claeis/ili2db pull request #418
Opened 2021-08-05 16:08 UTC by Philippluca

resolves #393

2021-08-06 09:13 UTC, claeis requested changes
``if(arg.startsWith(...))`` ist problematisch, weil es Optionen, die gleich beginnen, nicht unterscheiden kann. Darum besser eine Funktion ``isOption(String optionName)``, die auf nur-der-Optionsname oder der- Optionsname+"=" testet.

2021-08-06 09:13 UTC, claeis commented on src/ch/ehi/ili2db/AbstractMain.java
> +			EhiLogger.logAdaption(String.format("Could not parse boolean value <%s> for option <%s>.", value, arg.substring(0,indexEquals)));
muss eine Exception werfen und zum Abbruch führen.

2021-08-09 12:08 UTC, claeis requested changes
fehlt noch GpkgMain und FgdbMain

2021-08-09 13:09 UTC, merged

2022-12-09 10:59 UTC, signedav commented
@Philippluca @claeis Gibt es auch die Möglichkeit ein `--postScript` oder `iliMetaAttrs` zu "entfernen"? Ein leerer String ergibt einen Fehler. 

Es geht darum, dass wenn man ein metaConfig File übergibt, mit den manuellen Parameter einzelne übersteuern bzw. deaktivieren möchte, was mit den booleans dank dieser Implementierung funktioniert, nicht aber mit den Parametern, die einen Wert voraussetzen. Oder doch?

2022-12-13 08:11 UTC, signedav commented
Nichts zu übergeben wäre UX mässig verwirrend, weil normalerweise ja ein Parameter ohne Wert einem  `=true` entspricht. Deshalb halte ich es auch für Sinnvoll den Wert auf "nichts" zu setzen. Habe aber keine starke Meinung, ob `--postScript ""`, `--postScript NULL`.

Oder wäre analog zu dieser Implementierung hier auch `--postScript=false` eine Option?

2022-12-13 08:25 UTC, claeis commented
- ``--postScript ""`` würde zwar funktionieren, ist m.E. aber innerhalb Shell-Skripts schwierig richtig zu benutzen (=zu Fehleranfällig)
- ``--postScript=false`` würde auf der Kommandozeile gut funktionieren (aber wäre es das selbe wie ``--postScript false`` oder eben etwas anderes? finde ich wegen dieser Unklarheit auch ungeeignet)
- ``--postScript NULL`` (oder NIL oder UNDEFINED) ist meine Preferenz

2022-12-13 08:30 UTC, signedav commented
Eigentlich wär meines Erachtens `--postScript=false` am schönsten, um postScript zu deaktivieren. Normalfall wäre `--postScript=true test.sql` wobei aber natürlich das `true` nicht gebraucht würde und das Gegenteil eben `--postScript=false`.

Aber ich bin mit dir einig betreffend Unklarheit, weshalb `NULL` für mich auch eine gute Lösung ist. Und es ist auch logisch. Man setzt `--postScript` zwar, aber überschreibt den Wert auf NULL.