ili24: implement MULTISURFACE/MULTIAREA
claeis/ili2db pull request #436
Opened 2021-11-25 15:43 UTC by Philippluca

Resolves https://github.com/claeis/ili2db/issues/410
Requires https://github.com/claeis/iox-ili/pull/99

2021-12-02 11:36 UTC, Philippluca commented
@claeis Ich verstehe hier nicht warum der Build fehlschlägt. Kannst du dem nachgehen?

2021-12-08 09:19 UTC, claeis requested changes

2021-12-08 09:19 UTC, claeis commented on src/ch/ehi/ili2db/fromili/FromIliRecordConverter.java
> +				if(type instanceof AreaType || type instanceof MultiAreaType){
hier nur AreaType! (da nur für ITF)

2021-12-08 09:19 UTC, claeis commented on src/ch/ehi/ili2db/fromxtf/FromXtfRecordConverter.java
> +					 if(type instanceof AreaType || type instanceof  MultiAreaType){
nur AreaType! (da nur für ITF)

2021-12-08 09:19 UTC, claeis commented on src/ch/ehi/ili2db/fromxtf/FromXtfRecordConverter.java
> +						 if(type instanceof AreaType || type instanceof MultiAreaType){
nur AreaType, da nur für ITF

2021-12-08 09:19 UTC, claeis commented on src/ch/ehi/ili2db/toxtf/ToXtfRecordConverter.java
> +			}else if(type instanceof MultiSurfaceOrAreaType){
kann vereinfacht werden, da es in ITF kein MultiSurfaceOrAreaType gibt (also createItfLineTables und createItfAreaRef weglassen)

2021-12-08 09:19 UTC, claeis commented on src/ch/ehi/ili2db/toxtf/ToXtfRecordConverter.java
> +						 if(type instanceof AreaType || type instanceof  MultiAreaType){
nur AreaType (in ITF)

2021-12-13 13:28 UTC, merged