Ensure validity for imported SURFACE/MULTISURFACE geometries
claeis/ili2db pull request #441
Opened 2021-12-07 16:17 UTC by Philippluca

Fixes #437 for ili2pg

Requires `--strokeArcs` option enabled as `ST_MakeValid` only supports POINTS, MULTIPOINTS, LINESTRINGS, MULTILINESTRINGS, POLYGONS, MULTIPOLYGONS and GEOMETRYCOLLECTIONS for now.

Further information on Geometry Validation can be found in [PostGIS documentation](https://postgis.net/docs/postgis_usage.html#OGC_Validity)

2021-12-08 08:18 UTC, claeis requested changes
So gelöst, braucht es einen Schalter mit dem man das Verhalten beim --import an/auschalten kann (--enableSqlMakeValidGeometry). Weil ST_MakeValid macht ja evtl. viel mehr (das evtl. nicht zu einer gleichwertigen Geometrie führt), als das Problem "innerer Rand ist Teil des einen/äusseren Polygons" zu lösen.

2021-12-08 08:31 UTC, edigonzales commented
Wäre es nicht sinnvoller, wenn man es nicht mit einer PostGIS-Funktion löst, sondern applikatorisch zB mit JTS. Dann stimmen die Geometrien auch für alle anderen ogc-konformen DB-Flavours.

Im dümmsten Fall macht MakeValid ein Multipolygon aus einem Polygon. Das kann man dann nicht mehr speichern.

2021-12-08 08:50 UTC, claeis commented
> Wäre es nicht sinnvoller, wenn man es nicht mit einer PostGIS-Funktion löst, sondern applikatorisch zB mit JTS. Dann stimmen die Geometrien auch für alle anderen ogc-konformen DB-Flavours.
> 
> Im dümmsten Fall macht MakeValid ein Multipolygon aus einem Polygon. Das kann man dann nicht mehr speichern.

Ja, das Problem "innerer Rand ist Teil des einen/äusseren Polygons" (und nichts anderes) würde man besser in Iox2wkb (gilt ja für alle WKBs) lösen. Aber die hier nun implementierte Funktionalität ist auch nett (aber nur optional; darum die neue Kommandozeilen Option) , wenn man fehlerhafte Daten importieren/korrigieren will.

2021-12-10 14:23 UTC, Philippluca commented
@claeis Wir werden den Schalter `--enableSqlMakeValidGeometry` noch einbauen. 

@edigonzales Der in JTS verfügbare `GeometryFixer` ist in der in den ili-Tools verwendeten Version noch nicht verfügbar. Er funktioniert auch leicht anders als `ST_MakeValid`. Siehe [hier](http://lin-ear-th-inking.blogspot.com/2021/05/fixing-invalid-geometry-with-jts.html). Leider hat es da auch einen Namespace Wechsel gegeben.  Mit der Verwendung von `ST_MakeValid` stellen wir sicher, dass keine invalide Geometrie in der DB landet.

> Ja, das Problem "innerer Rand ist Teil des einen/äusseren Polygons" (und nichts anderes) würde man besser in Iox2wkb (gilt ja für alle WKBs) lösen.

Die Regeln für Validity zu erfüllen, ist für die Repräsentation einer Geometrie keine Voraussetzung. ESRI verwendet für ihre definition von Validity andere Regeln. Für ili2fgdb müsste diese "Korrekur" in Iox2wkb wieder rückgängig gemacht werden.

2021-12-10 14:45 UTC, edigonzales commented
Ich finde die Variante ST_MakeValid als einzige Lösung für dieses Problem nicht gut:
- Sie funktioniert nur mit PostGIS
- ST_MakeValid kann dazu führen, dass geflickte Geometrien nicht mehr importiert werden können, weil aus einem Polygon ein Multipolygon gemacht wurde.
- Das Entfernen von erlaubten Overlaps wird auch in ili2db gemacht und nicht mit ST_MakeValid

> Die Regeln für Validity zu erfüllen, ist für die Repräsentation einer Geometrie keine Voraussetzung. ESRI verwendet für ihre definition von Validity andere Regeln. Für ili2fgdb müsste diese "Korrekur" in Iox2wkb wieder rückgängig gemacht werden.

Wäre das schlimm? Es wäre doch auch für fdgb noch immer ein gültiges Polygon (nach der Korrektur in Iox2wkb)?

2021-12-10 15:03 UTC, claeis commented
> ESRI verwendet für ihre definition von Validity andere Regeln. Für ili2fgdb müsste diese "Korrekur" in Iox2wkb wieder rückgängig gemacht werden.

Genau, darum verwendet ja ili2fgdb auch nicht Iox2wkb (sondern Iox2fgdb; wo diese anderen Regeln implementiert sind...)

2021-12-10 15:19 UTC, claeis commented
> a, das Problem "innerer Rand ist Teil des einen/äusseren Polygons" (und nichts anderes) würde man besser in Iox2wkb (gilt ja für alle WKBs) lösen.

+- der Code in iox-ili:LineSet.buildBoundaries()

2022-01-14 14:46 UTC, Philippluca commented
@edigonzales Wir werden nach Rücksprache mit @claeis die Korrektur direkt in Iox2wkb umsetzten. Mit einem Flag kann die Korrektur abgeschaltet werden. 

+- Wird der Alogo das gleiche wie iox-ili:LineSet.buildBoundaries() machen: Heisst im Fliesstext: Wir korrigieren sich in Stützpunkten berührende Ringe von Polygonen.

2022-01-24 15:34 UTC, closed without merging