Add basket unique constraint support
claeis/ili2db pull request #522
Opened 2023-10-02 07:26 UTC by Philippluca

REQ: Fix of [ili2db: Unique constraints are not generated #493](https://github.com/claeis/ili2db/issues/493)
REQ: [ili2c: Eindeutigkeitsbedingungen auf den einzelnen Transfer#90](https://github.com/claeis/ili2c/issues/90)
REF: [ili24: Eindeutigkeitsbedingungen auf den einzelnen Transfer#518](https://github.com/claeis/ili2db/issues/518)

2023-10-12 12:35 UTC, patrickackermann approved these changes

2023-10-18 12:31 UTC, claeis requested changes
bitte keine Aenderungen am build.gradle die nichts mit dem Issue zu tun haben

2023-11-22 10:37 UTC, claeis requested changes
Bitte Tests ergänzen

2023-11-22 12:31 UTC, Philippluca commented
> Bitte Tests ergänzen

Test Expectations sind wohl abhängig davon, wie https://github.com/claeis/ili2db/issues/493 umgesetzt wird.

2023-11-29 15:31 UTC, merged